### PR TITLE
Implements support for Visual Studio Templates

### PR DESCRIPTION
**Pull request by sameera**
Matches user's input to a Visual Studio Template when available
and enables quick creation of C# classes and interfaces by using
c:*class_name* and i:*interface_name* syntax in the "Add New File"
dialog box.

### CODE REVIEW

**Comment by madskristensen** [comment]
Awesome!!!

Should we make it so that the C#/VB interface templates are invoked simply by any file name starting with a capital `i` and the second character be any uppercase char. For instance:

IFoo.cs wil automatically invoke the C# interface template. Dummy regex: `^I[A-Z].+\.cs$`

**Comment by sameera** [comment]
@madskristensen 
+1. Makes sense. I personally don't use that convention (I've been working with Java folks for so long :) which is why I didn't add it.
I'll make the following changes:
* Support `I<interface_name>.cs`, `I<interface_name>.vb` convention for adding interfaces
* `<name>.cs` will default to C# classes (rather than empty code file), since this is the more common scenario
* Assign `e:<name>.cs` syntax to creating an empty code file (with namespace declared)

I think, while I'm at it, I might as well move the patterns to an external file. Then even without a Options  dialog page, anyone can add their own patterns. So, this pull will take some time.
May be you can merge this pull in the meantime, so that anyone else who wants the code now, can get it? :)

**Comment by sameera** [comment]
So, now:
* `I<name>.cs` or `I<name>.vb` will automatically generate Interfaces
* `<name>.cs` will generate a C# class

Patterns can be managed by editing the `%appdata%\VisualStudio.AddAnyFile\Patterns.json` file. 
I dropped JSON.net and stuck with System.Runtime.Serialization.Json which doesn't let me pretty print the JSON. So, if you want to edit this file, you can use a tool such as JSON Viewer plugin in Notepad++

**Comment by sameera** [comment]
Did minor refactoring so that the user is not prompted for a file name if there's no project selection on the Solution Explorer.

**Comment by madskristensen** [comment]
I can merge this as soon as the merge conflicts have been resolved. Then I'll also fix the issue with the references to VS2015-only assemblies.

**Comment by sameera** [comment]
I created PR #14  merging latest from this repo.

**Pull request closed without merging**
